var pokemonData =[
  { id:0,
    name:'Pikachu',
    image:'./images/pokemonSprite.png',
    hp : '100',
    type : 'electric',
    level: '1',
    attacks :{
        Thunder:'25',
        Shock:'10',
        wildCharge:'10',
        tailSlap:'20'},
    //power :'40',
  },
  { id:1,
    name:'Balbasur',
    image:'./images/balbasurSprite.png',
    hp : '100',
    type : 'grass',
    level : '1',
    attacks : {Growl:'10',
                Whip:'10',
                BulletSeed:'20',
                Tackle:'25'},
  },
  { id:2,
    name:'Squirtel',
    image:'./images/squirtelSprite.png',
    hp :'100',
    type : 'water',
    level: '1',
    attacks :{Bubble:'10',
              aquaTail:'20',
              shellAttack:'30',
              waterTank:'20'}
  },
  { id:3,
    name:'Eevee',
    image:'./images/eeveeSprite.png',
    hp : '70',
    type : 'normal',
    level: '1',
    attacks :{helpingHand:'10',Tackle:'15',tailWhip:'10',sandAttack:'20'}
  },
  { id:4,
    name:'Caterpie',
    image:'./images/caterpieSprite.png',
    hp : '70',
    type : 'bug',
    level : '1',
    attacks : {BugBite:'14',
                Struggle:'15',
                Tackle:'20',
                stringShot:'10'}
  }
]