var pokemonData =[
  { id:0,
    name:'Pikachu',
    image:'./images/pokemonSprite.png',
    hp : '300',
    type : 'electric',
    level: '1',
    attacks :['Thunder','Shock','Wild-Charge'],
    power :'40',
  },
  { id:1,
    name:'Balbasur',
    image:'./images/balbasurSprite.png',
    hp : '300',
    type : 'grass',
    level : '1',
    attacks : ['Growl','Whip','Toggle','Tackle'],
    power : '40',
  },
  { id:2,
    name:'Squirtel',
    image:'./images/squirtelSprite.png',
    hp :'300',
    type : 'water',
    level: '1',
    attacks :['Bubble','Aqua-tail'],
    power :'40',
  },
  { id:3,
    name:'Eevee',
    image:'./images/eeveeSprite.png',
    hp : '170',
    type : 'normal',
    level: '1',
    attacks :['Helping-Hand','Tackle','Tail-Whip','Sand-Attack'],
    power :'30',
  },
  { id:4,
    name:'Caterpie',
    image:'./images/caterpieSprite.png',
    hp : '170',
    type : 'bug',
    level : '1',
    attacks : ['BugBite','Struggle'],
    power : '40',
  }
]